require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/InverseOf:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false